Backend/blog/urls.py
from django.urls import path
from .views import (
	BlogHomePageView,
	PostDetailView,
)

app_name='blog'

urlpatterns = [
	path('', BlogHomePageView.as_view(), name='home'),
	path('<slug>/', PostDetailView.as_view(), name='post-detail'),
]

Backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import (
    HomePageView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='blog')),
]

Backend/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone 

class Category(models.Model):
	name = models.CharField(max_length=100)

	def __str__(self):
		return self.name


class Post(models.Model):

	class PostObjects(models.Manager):
		def get_queryset(self):
			return super().get_queryset() .filter(status='published')

	options = (
		('draft', 'Draft'),
		('published', 'Published'),
	)
 # campos
	category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
	title = models.CharField(max_length=255)
	excerpt = models.TextField(null=True)
	content = models.TextField()
	slug = models.SlugField(max_length=250, unique_for_date='published', null=False, unique=True)
	published = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
	status = models.CharField(max_length=10, choices=options, default='draft')
	objects = models.Manager() 
	postobjects = PostObjects()


	class Meta:
		ordering = ('-published',)
	
	def __str__(self):
		return self.title

class Comment(models.Model):

	post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name="comments")
	name = models.CharField(max_length=50)
	email = models.EmailField()
	content = models.TextField()
	publish = models.DateTimeField(auto_now_add=True)
	status = models.BooleanField(default=True)

	class Meta:
		ordering = ("publish",)

		def __str__(self):
			return f"Comment by {self.name}"

Backend/blog/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.views.generic.detail import DetailView
from .models import Post

# Create your views here.
class BlogHomePageView(TemplateView):
	template_name="blog/index.html"

	# cargamos desde la base de datos.
	# definimos get_context_data - **kwargs / selec toda las categorias.
	def get_context_data(self, **kwargs):
		# siempre se declara un contexto.
		context = super().get_context_data(**kwargs)
		# referencia a nombres de la base de datos.
		context["posts"] = Post.postobjects.all()
		return context

class PostDetailView(DetailView):
	model = Post
	template_name = 'blog/post-detail.html'
	# cargamos el contexto
	context_object_name = 'post'
	# definimos content_data
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		post = Post.objects.filter(slug=self.kwargs.get('slug'))
		return context

Backend/core/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
	template_name = 'index.html'

Backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% comment %} <link rel="stylesheet" href="text/css" href="{% static '/css/style.css' %}" media="screen"/> {% endcomment %}
	<title>{% block title %}{% endblock title %}</title>
</head>
<body>
	
	{% block content %}
		BaseHTML
	{% endblock content %}
		
</body>
</html>

Backend/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}APP-FINAL blog home page{% endblock title %}
{% block content %}
Blog HomePage

{% for post in posts %}
<!-- declaramos urls en django -->
<!--quese_yo2/'blog:post-detail'???-->
<a href="{% url 'blog:post-detail' slug=post.slug %}"> 
	{{ post.title }}
	{{ post.excerpt|truncatechars:50}}
</a>
{% endfor %}

{% endblock content %}

Backend/templates/blog/post-detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
Post Detail View
{{post.title}}
{{post.content|truncatechars:50}}
{% endblock content %}

Backend/templates/index.html
{% extends 'base.html' %}
{% block title %}APP-FINAL HomePage{% endblock title %}
{% block content %}
<a href={% url 'home' %}>
Home page
</a>
<a href={% url 'blog:home' %}>
Blog
</a>

{% endblock content %}

Backend/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Signin Template · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
<link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  <form>
    <img class="mb-4" src="/docs/5.1/assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>


    
  </body>
</html>